version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql_8
    environment:    
      MYSQL_ROOT_PASSWORD: "password"      
    ports:
      - "3307:3306"   