# versão do docker-compose
version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_docker
    environment:
    - MYSQL_ROOT_PASSWORD=password
    ports:
    - 3306:3306

networks:
  default:
    name: bloco_26_net
