version: '3'
services:
  node:
    image: node:16
    container_name: bloco_22
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
    - ./:/app
    
networks:
  default:
    name: bloco_22_net