version: '3'

services:
  node:
    image: node:16-alpine
    container_name: bloco_22
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3030:3000

networks:
  default:
    name: bloco_22_net