version: '3'

services:
  node:
    image: node:16-alpine
    container_name: bloco_222
    tty: true
    stdin_open: true
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3030:3000

networks:
  default:
    name: bloco_222_net
