version: '3.1'

services:

  mongo:
    image: mongo
    ports:
      - 8080:27017
    volumes:
      - ./backup:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example 