version: '3'

services:
  node:
    image: node:16
    container_name: bloco_2
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
    - ./:/app
    ports:
      - 3010:3000
 
networks:
  default:
    name: bloco_2_net
