version: '3.1'

services:

  mongo:
    image: mongo
    container_name: bloco_30
    ports:
      - 27017:27017
    volumes:
      - ./backup:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
networks:
  default:
    name: bloco_30_net